POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RfdXNyIiwiaWQiOiI2MjYwMzY5ZTljYmJlNDc0NzAyMzMxM2YiLCJpYXQiOjE2NTA0NzMxMTZ9.w1T2csmfbBwcA-i4fPp92vBtFk_wSNMFFF7vAcfz4oQ

{
  "title": "yse, broke it down",
  "author": "kai",
  "url": "http://needtologin.org",
  "likes": "5"
}