POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImxvZ2ludXNyIiwiaWQiOiI2MjVmYzIzNDZmZjY3OThhZWUxMTlhYjEiLCJpYXQiOjE2NTA0NDI4MTAsImV4cCI6MTY1MDQ0NjQxMH0.lW5Ee6YcrGtiubVSFh6TOw5G29GNe-LNTNvfpqa8HkQ

{
  "title": "loginusr is posting for fifth time",
  "author": "loginusr",
  "url": "http://needtologin.org",
  "likes": "5",
  "userId": "625fc2346ff6798aee119ab1"
}